from . import load


NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}


NODE_CLASS_MAPPINGS.update(load.NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(load.NODE_DISPLAY_NAME_MAPPINGS)
